#!/bin/bash

#SSH_URI=_SSH_URI_
#SSH_USER=_SSH_USER_
#SSH_PASS=_SSH_PASS_

if [[ -z "$SSH_URI" ]] || [[ -z "$SSH_USER" ]] || [[ -z "$SSH_PASS" ]]
then
  echo "[!] Please, provide the following environment variables:"
  echo '    - $SSH_URI'
  echo '    - $SSH_USER'
  echo '    - $SSH_PASS'
  echo '    - [$SSH_ARGS]'
  echo '    - [$SSH_CMD]'
  exit 1
fi

SSH_HOST=$(echo $SSH_URI | awk -F: '{print $1}')
SSH_PORT=$(echo $SSH_URI | awk -F: '{print $2}')

expect <<EOF
spawn ssh $SSH_ARGS -p $SSH_PORT $SSH_USER@$SSH_HOST $SSH_CMD
while (1) {
  expect {
    -re ".*assword:.*" { send "$SSH_PASS\r" }
    -re "Are you sure *" { send "yes\r" }
    eof { break }
  }
}
EOF
